[project]
name = "nr-epd-ventilation-index"
version = "0.1.0"
description = "BC ventilation index bulletin generator"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.ruff]
line-length = 120