name: Run Application

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

concurrency:
  group: run-application
  cancel-in-progress: false

jobs:
  run_application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run application
        run: uv run main.py

      - name: Commit and push report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          fi
          git add reports/.
          git commit -m "Automated commit of application output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"