name: Run Application

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  run_application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run application
        run: uv run main.py

      - name: Commit and push report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports/.
          git commit -m "Automated commit of application output"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}