name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - name: Install Python
        run: uv python install

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run Unit Tests
        run: uv run pytest tests
